# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 094a3e67781fe643861416352b7f241cde0112132d26d56df8e745f0ed7ae70f2557c14f06a8c98030893e5a089bb807e7ec4e2d739d9c8c6d60f244735c8655

test:
  secret_key_base: 4a69715b023367a4844cbfb371438ffb29d527b5668abc86cb55efb7b4b9462e43f0dce9d1e035aa3497d0d666680136bf0904356876c218535a154427efeb9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
