# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ba78fd0531d1f0ecc7456a8b91ecf39043b7d69188cd61ebfc1f3c0e2bbc043dae39a28e87afb0a0e92aa4a1f10d8caabd4a0806d470a21f1563f6324cc83cc

test:
  secret_key_base: ab4a01d54496f246991fb015ed459aca661c37d6cc91f2aad0359dc72bc51a7a3fa905ae3e545586cc8dbf95dfbb7c43ae55499519dea45003f5c36f9c612157

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
